// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvTgJPIA45YloNMTkedbbdKtlqeQp-_k',
    appId: '1:380872090513:web:4361bad711a49072d4f030',
    messagingSenderId: '380872090513',
    projectId: 'todo-app-c90a9',
    authDomain: 'todo-app-c90a9.firebaseapp.com',
    storageBucket: 'todo-app-c90a9.appspot.com',
    measurementId: 'G-TX84PSV4EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtcJJocIk3hwO1Jnhmc9cy5v1k4RBYX8',
    appId: '1:380872090513:android:4db02aab77063528d4f030',
    messagingSenderId: '380872090513',
    projectId: 'todo-app-c90a9',
    storageBucket: 'todo-app-c90a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBPEviuzBwVu09G4WGo5QR9frI0gBXio',
    appId: '1:380872090513:ios:1327a3151d20673fd4f030',
    messagingSenderId: '380872090513',
    projectId: 'todo-app-c90a9',
    storageBucket: 'todo-app-c90a9.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

}